[package]
name = "socotra"
version = "0.1.0"
authors = []
edition = "2024"
description = "Part of Solana RPC stack for sealed data"
homepage = ""
repository = ""
license = ""
keywords = ["solana", "rpc"]
publish = false

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.30", features = ["derive"] }
futures = "0.3.31"
indicatif = "0.18.0"
itertools = "0.14.0"
maplit = "1.0.2"
num_cpus = "1.16.0"
prost = "0.14.1"
richat-client = "5.0.0"
richat-proto = "5.0.0"
rocksdb = "0.24.0"
solana-accounts-db = "~2.3.0"
solana-sdk = "~2.3.0"
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["ansi", "env-filter"] }

[lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"

[profile.release]
lto = true
codegen-units = 1
