monitoring:
  logs_json: false
  otlp_endpoint:
state:
  endpoint: http://127.0.0.1:8899
  segments: 16
storage:
  path: ./db
  compression: none # none, snappy, zlib, bz2, lz4, lz4hc, zstd
source:
  tokio:
    worker_threads: null # Number of threads in Tokio runtime, by default all available cores
    affinity: null # Pin threads to specific CPUs, optional (taskset syntax)
  # reconnect:
  #   backoff_init: 100ms
  #   backoff_max: 1s
  endpoint: http://127.0.0.1:10000
  ca_certificate: null
  connect_timeout: null
  buffer_size: null
  http2_adaptive_window: null
  http2_keep_alive_interval: null
  initial_connection_window_size: null
  initial_stream_window_size: null
  keep_alive_timeout: null
  keep_alive_while_idle: false
  tcp_keepalive: 15s
  tcp_nodelay: true
  timeout: null
  max_decoding_message_size: 4_194_304 # 4MiB, better set to 16MiB (because account messages can be more than 10MiB)
  compression: # Optional compression, not recommended due to high traffic volume
    accept: [] # valid: gzip, zstd
    send: [] # valid: gzip, zstd
  x_token: null
banks:
  updates_channel_size: 512
rpc:
  endpoint: 127.0.0.1:9000 # RPC endpoint, implement same JSON-RPC API as Agave
  tokio:
    worker_threads: null # Number of threads in Tokio runtime, by default all available cores
    affinity: null # Pin threads to specified CPUs, optional
  body_limit: 10KiB # JSON-RPC body limit
  extra_headers: # Extra headers added to response
    # access-control-allow-origin: "*"
    # access-control-max-age: 86400
    # access-control-allow-methods: OPTIONS, POST
  request_timeout: 60s
  request_channel_capacity: 4_096 # Queue size of requests to read threads (be aware, one JSON-RPC request can contain multiple requests)
